import dotenv from "dotenv";
dotenv.config();


const { PORT,DB_URL, INSTAGRAM_CLIENT_ID, INSTAGRAM_CLIENT_SECRET, INSTAGRAM_REDIRECT_URI, YOUTUBE_API_KEY , encrypt_decrypt_key, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI, FRONTEND_URL} = process.env

const SECRET_KEY = encrypt_decrypt_key || '';

export { PORT,DB_URL, INSTAGRAM_CLIENT_ID, INSTAGRAM_CLIENT_SECRET, INSTAGRAM_REDIRECT_URI, SECRET_KEY, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI, FRONTEND_URL , YOUTUBE_API_KEY}